baseURL: "https://manngajjar.netlify.app"
languageCode: "en-us"
title: "Gajjar Mann Bipinchandra"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Gajjar Mann Bipinchandra"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/NEUlogo.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Gajjar Mann Bipinchandra" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Mann."
    subtitle: "Data Analyst/Business Intelligence Analyst/Data Scientist/Machine learning Engineer"
    content: "A data analyst committed to using advanced analytics tools to uncover strategic insights, turning complex data into clear, actionable knowledge efficiently."
    image: /images/Mann.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "RESUME"
      url: "https://drive.google.com/file/d/1UhmngAH6sS7YAzsNwp5v9JP1vr7-tGha/view?usp=sharing"
      download: true
      newPage: false
    socialNetworks:
      github: https://github.com/Gmann13
      linkedin: https://www.linkedin.com/in/manngajjar/
      

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/Mann2.jpg"
    content: |-
      I am a Highly skilled Data Analyst, Business Analyst and Machine learning enthusiast with extensive experience in data analysis, predictive modeling, and business intelligence. Proficient in SQL, Python, and advanced analytics tools, with expertise in designing data-driven solutions that enhance decision-making and operational efficiency. Proven ability to deliver impactful insights through data visualization and collaboration with cross-functional teams. Dedicated to driving innovation and solving complex business problems.
      enable: true
      title: "My expertise spans across critical data analytics tools such as:"
      items:
        - "Python"
        - "R (RStudio)"
        - "SQL"
        - "Machine Learning"
        - "GIT"
        - "Tableau"
        - "Power BI"
        - "Big Data"
        - "Data Management and Warehousing"
        - "Microsoft Office Suite (Excel, Word, PowerPoint)"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Data Analyst/Project Manager"
        company: "Rebecca Everlene Trust Company"
        date: "October 2024 - Present"
        tab_id: "rebecca"
        content: |-
          - Gathered and analyzed data from JIRA and monday.com, ensuring team activities were logged consistently, resulting in improved transparency and workflow efficiency.
          - Managed MySQL databases to ensure accuracy and consistency of data infrastructure.
          - Built and maintained interactive dashboards using Tableau for real-time insights, enhancing operational efficiency by 20%.
          - Applied Python scripts and Alteryx workflows to automate data processing, reducing manual effort by 40%.
          - Supported end-users with data access, training, and troubleshooting to ensure seamless utilization of systems.
      
      - job: "Data/Business Analyst"
        company: "The Roux Institute"
        date: "July 2023 - December 2023"
        tab_id: "Roux"
        content: |-
          - Conducted data analysis and market research for healthcare startups, boosting customer engagement by 25% through actionable insights.
          - Developed data-driven solutions, increasing predicted revenue by 15%.
          - Designed and presented dashboards using Power BI to effectively communicate trends and performance metrics.
          - Collaborated with cross-functional teams to improve operational efficiency by 10%.
          
      - job: "Data Analyst"
        company: "Bion International Pvt Ltd"
        date: "May 2019 - August 2022"
        tab_id: "Bion"
        content: |-
          - Led transformative initiatives that enhanced decision-making speed by 20% through advanced data-driven insights and strategic analysis for company leadership.
          - Authored comprehensive marketing and supply chain performance reports, successfully reducing logistics costs by 10% by identifying and addressing inefficiencies.
          - Developed scalable SQL-based models and innovative Python scripts to streamline data analysis, significantly boosting operational efficiency and automating repetitive tasks.
          - Reengineered delivery workflows, resolving critical shipment issues and improving customer satisfaction metrics through precise data interventions and proactive problem-solving.
          - Implemented process automation that reduced manual reporting time by 30%, enabling faster access to insights and improved resource allocation.
          
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Masters in Engineering Management"
        school:
          name: "Northeastern University, Boston"
        date: "2022 - 2024"
        content: "Concentration: Data Analytics and Machine Learning Engineering"
        GPA: "3.4 out of 4.0"
        content: |-
          Relevant Coursework:
            - Database Management and Design, Data Mining, Data Warehousing & SQL, Data Visualization, Machine Learning, Sociotechnical Systems, Project Management, Deterministic Operations Research.
      - title: "Bachelor of Technology in Mechatronics Engineering"
        school:
          name: "Ganpat University"
        date: "2018 - 2022"
        GPA: "3.5 out of 4"
        content: |-
          Relevant Coursework:
            - Coursework: Computational Intelligence Techniques, Robotics, Digital Image Processing and machine vision, Industrial Internet of things, Sensor system, Advanced Machine Learning.

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Traffic Volume Prediction
        content: This project utilizes a machine learning approach with a RandomForestRegressor model to predict traffic volume based on the Metro Interstate Traffic Volume dataset from the UCI Machine Learning Repository. By leveraging features like weather conditions, date-time attributes, and lagged traffic volumes, the project aims to provide accurate predictions for traffic management and urban planning.
        image: /images/projects/Traffic Volume Prediction.jpg
        featured:
          name: View Project
          link: https://github.com/Gmann13/Traffic-Projection
        badges:
          - "Experiential Learning (Data Analyst)"
          - "Jupyter"
          - "Python"
          - "Pandas"

      - title: From Browsing to Buying- Predicting Purchase Intentions in Online Shoppers
        content:  This project leverages machine learning techniques to predict whether an online shopper will make a purchase using the Online Shoppers Purchasing Intention Dataset. By analyzing session data, including user behavior, engagement metrics, and temporal attributes, the project aims to provide actionable insights for e-commerce platforms. The best-performing model, Support Vector Machine (SVM), achieved an ROC AUC score of 0.92, highlighting its effectiveness in distinguishing between purchasing and non-purchasing sessions. This predictive capability can enhance marketing strategies, optimize customer engagement, and drive sales conversion rates.
        image: /images/projects/Purchase Prediction.png
        featured:
          name: View Project
          link: https://github.com/Gmann13/Predicting-Purchase-Intentions-in-Online-Shoppers
        badges:
          - "Big Data"
          - "Machine Learning"
          - "Python"
          - "Pandas"

      - title: Inventory Management System
        content: This project is a robust Inventory Management System designed to streamline inventory tracking, sales reporting, and transaction management. It includes the creation of a comprehensive database with an Entity-Relationship Diagram (ERD), well-structured tables, views for reporting (e.g., daily sales, stock, and customer transactions), and PL/SQL procedures for customer and supplier management. The system enforces security through user roles and permissions while providing actionable insights into sales trends, inventory levels, and customer behavior, making it an efficient solution for inventory operations.
        image: /images/projects/Inventory Management System.jpeg
        featured:
          name: View Project
          link: https://github.com/Gmann13/INVENTORY-MANAGEMENT-SYSTEM
        badges:
          - "Oracle PL/SQL"
          - "SQL"
          - "ERD Development"
          - "PL/SQL"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: mann.gajjar02@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      github: https://github.com/Gmann13
      linkedin: https://www.linkedin.com/in/manngajjar/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
